# docker-compose is used only for development.
version: "3"

services:
  web:
    platform: linux/amd64
    build:
      context: ./app
    volumes:
      - .:/app
    ports:
      - 3000:3000
    env_file: .env
    restart: always

  redis:
    # For development purpose.
    image: redis:6.2.6
    command: redis-server --requirepass ${CELERY_REDIS_PASSWORD} --port 6379
    container_name: redis
    hostname: redis
    labels:
      - "name=redis"
      - "mode=standalone"
    ports:
      - 6379:6379
    env_file: .env

  rabbitmq:
    image: rabbitmq:latest
    volumes:
      - "./rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf"
    ports:
        - "5672:5672"

  worker:
    build: ./app
    command: celery -A app.celery.worker worker -l info
    volumes:
      - .:/usr/src/app
    env_file: .env
    depends_on:
      - web
      - redis

  dashboard:
    # For Development purpose
    build: ./app
    command: celery -A app.celery.worker flower
    ports:
      - 5555:5555
    env_file: .env
    depends_on:
      - web
      - redis
      - rabbitmq
      - worker
